### ISSUE TITLE
Cobuy as Value Flows

### ISSUE THREAD

**Issue by fosterlynn** [root-systems/cobuy-meta#2]
@ahdinosaur is this a good way to give feedback?  (Ref. https://github.com/valueflows/valueflows/issues/127)

I just started looking and have one initial comment, will have more when I get deeper.

"Supplier" is probably a relationship type, not an agent type.  Like maybe one of your members grows a lot of garlic and offers it to the coop or buying club.

**Comment by ahdinosaur** [comment]
this is great, thanks @fosterlynn

**Comment by fosterlynn** [comment]
I did another round of looking.

I'm not sure you want to create a new Agent (purchase group) for each order.  The people would just naturally fall into relationships around the order when they express their requests for that order.  And I believe the Coop is the agent that makes the order, if I am reading correctly.  That is, the purchase group doesn't have that much agency.  I do read that a person can be a facilitator for a purchase group.  But perhaps that could be a work assignment with type of work = facilitation (a resource type) rather than a role of a group?

Note: Please ignore the above if it doesn't feel right to you.  To me it is a gut feeling that Agents (Groups) should be a bit more permanent, and people can associate around a particular batch of work in other ways (including say making an order). 

This could be one or a series of Processes with different work inputs, and also of course Transfers/Exchanges, maybe first between the supplier and the coop, then between the coop and each orderer?

I don't know if we will end up with Order in the VF vocab or not.  A customer/supplier order could be an Exchange or a set of Transfers with commitments for each item ordered and to pay the supplier.  A "work order" could be a set of processes that together create one or more things, like say an order.  Or maybe those could be combined, we haven't explored all of that territory.  I think we will need something like work order, to group processes into a logical grouping with an output, which is what you are using the purchase group for.  This might be like the little-p process.

I hope that wasn't totally convoluted!  Questions welcome, or @ahdinosaur if you want to work through this together sometime in a call, that would be pretty interesting.

**Comment by ahdinosaur** [comment]
hey @fosterlynn @bhaugen, just a heads up, i'm starting [development of Cobuy](https://github.com/enspiral-root-systems/cobuy) using [`catstack`](https://github.com/enspiral-root-systems/catstack).

the first release will be the second and third screens on the first image: basically enough to demo how many people can input their preferences on a bulk order and see the result.

![cobuyflow-repeatuser](https://cloud.githubusercontent.com/assets/719605/23248222/27a6d670-fa03-11e6-8ef5-d6bec6f8a573.jpg)

![newuserflow](https://cloud.githubusercontent.com/assets/719605/23248235/31dffcde-fa03-11e6-8f96-5866caddab40.jpg)

my plan is to get something working, then have a discussion on how our data model converges with the [latest Value Flows discussions](https://github.com/valueflows/valueflows/pull/176) (except using an append-only log of data messages like Scuttlebutt instead of RDF-style linked open data).

sorry for the delay, but it's happening!

**Comment by ahdinosaur** [comment]
some notes on initial data model:

```
- supplier
  - name: string
- order
  - [resource]
- resource type
  - ([resource types])
  - name: string
- supply type
  - supplier
  - resource type
  - batch size: quantity
  - [supply cost]
- supply cost
  - min batches: number
  - price per batch: quantity
- quantity
  - value: number
  - unit: enum
```

where `(...)` means optional and `[...]` means many.

/cc @mischa-saunders @bill-burgess

**Comment by fosterlynn** [comment]
@ahdinosaur great!!  Looking forward to your demo...

>my plan is to get something working, then have a discussion on how our data model converges with the latest Value Flows discussions (except using an append-only log of data messages like Scuttlebutt instead of RDF-style linked open data).

Your initial data model is a bit confusing to me, but that's ok.  :)  I'd love to map it to VF with you whenever you want!  Or just walk through it together if that would be helpful to you.

Will be very interesting to see how this plays out in Scuttlebutt!  I think it is important to have VF support more than RDF-style data.

**Comment by ahdinosaur** [comment]
another round of data modelling! :tada: 

---

data model included as part of [`dogstack-agents`](https://github.com/dogstack/dogstack-agents)

```yml
- agents
  - id
- agentCredentials
  - type
- agentProfiles
  - id
  - agentId
  - name
  - image
  - description
- agentRelationships
  - sourceAgentId
  - relationshipType
  - targetAgentId
  - scope
- agentRelationshipTypes
  - id
  - name
  - description
```

---

rest of data model overview:

(inspired by https://github.com/valueflows/valueflows/pull/115 and https://github.com/enspiral-root-systems/nanox/issues/11)

```yml
- resourceType
  - id
  - name
  - image
  - description
- resource
  - id
  - resourceType
  - location
- location
  - id
  - name
  - image
  - description
- template
  - action: json
  - paramsSchema: json
- action
  - source
  - type: enum(give)
  - target
  - quantity
    - unit
    - value
    - if quantity is for consumer intent, it has:
      - desiredValue
      - minimumValue
      - maximumValue
    - if quantity is for supplier commitment, it has:
      - minimumValue
  - resource
- signal
  - agentId
  - type: enum(intent, plan, flow)
  - template
  - params: json
- quantity
  - id
  - value
  - unit: enum(kg, resource)
- unit
  - id
  - name
  - abbreviation
  - dimension
  - description
```

---

Cobuy process design using data models:

![img_20170605_163130](https://cloud.githubusercontent.com/assets/719605/26770691/ff3e7616-4a0c-11e7-91aa-1480aeeb1ec3.jpg)

## (1) supplier inventory

template

```yml
name: sell
action:
  - source: ${supplier}
    type: give,
    target: ${consumer}
    quantity:
      value: ${quantity}
      unit: each
      minimum: ${minimum}
    resource: ${product}
  - source: ${consumer}
    type: give
    target: ${supplier}
    quantity:
      value: ${price} * ${quantity}
      unit: each
    resource: ${currency}
schema:
  type: 'object'
  properties:
    supplier:
      type: 'string'
      format: 'id'
    consumer:
      type: 'string'
      format: 'id'
    price:
      type: 'string'
      format: 'decimal'
    quantity:
      type: 'string'
      format: 'decimal'
    minimum:
      type: 'string'
      format: 'decimal'
```

the data IS the user interface!

signal

```yml
agent: Supplier
type: intent
template: sell
params:
  supplier: me
  price: 1
  minimum: 10
```

## (2) individual consumer pledge

template

```yml
name: pre-buy
action: 
  - source: ${supplier}
    type: give,
    target: ${consumer}
    quantity:
      desired: ${desired}
      minimum: ${minimum}
      maximum: ${maximum}
      unit: each
    resource: ${product}
  - source: ${consumer}
    type: give
    target: ${supplier}
    quantity:
      value: ${price} * ${quantity}
      unit: each
    resource: ${currency}
schema:
  type: 'object'
  properties:
    supplier:
      type: 'string'
      format: 'id'
    consumer:
      type: 'string'
      format: 'id'
    resource:
      type: 'string'
      format: 'id'
    price:
      type: 'string'
      format: 'decimal'
    desired:
      type: 'string'
      format: 'decimal'
    minimum:
      type: 'string'
      format: 'decimal'
    maximum:
      type: 'string'
      format: 'decimal'
```

signal

```yml
agent: Consumer
type: intent
template: pre-buy
params:
  consumer: me
  supplier: them
  resource: avocado
  price: 1
  minimum: 1
  desired: 2
  maximum: 3
```

## (3) consumer group order

```yml
name: buy
action: 
  - source: ${supplier}
    type: give
    target: ${consumer}
    quantity:
      value: ${quantity}
      unit: each
    resource: ${product}
  - source: ${consumer}
    type: give
    target: ${supplier}
    quantity:
      value: ${cost}
      unit: each
    resource: ${currency}
schema:
  type: 'object'
  properties:
    supplier:
      type: 'string'
      format: 'id'
    consumer:
      type: 'string'
      format: 'id'
    resource:
      type: 'string'
      format: 'id'
    quantity:
      type: 'string'
      format: 'decimal'
    cost:
      type: 'string'
      format: 'decimal'
    currency:
      type: 'string'
      format: 'id'
```

signal

```yml
agent: ConsumerGroup
type: plan
intent: consumer intents
params:
  consumer: us
  supplier: supplier
  resource: avocado
  quantity: 10
  cost: $100
  currency: NZD
```

### (4) consumer group order received

signal

```yml
agent: ConsumerGroup
type: flow
input: consumer group plan
params:
  consumer: us
  supplier: supplier
  resource: avocado
  quantity: 8
  cost: $100
  currency: NZD
```

**Comment by ahdinosaur** [comment]
> I'm not sure you want to create a new Agent (purchase group) for each order. The people would just naturally fall into relationships around the order when they express their requests for that order. And I believe the Coop is the agent that makes the order, if I am reading correctly. That is, the purchase group doesn't have that much agency. I do read that a person can be a facilitator for a purchase group. But perhaps that could be a work assignment with type of work = facilitation (a resource type) rather than a role of a group?
>
> Note: Please ignore the above if it doesn't feel right to you. To me it is a gut feeling that Agents (Groups) should be a bit more permanent, and people can associate around a particular batch of work in other ways (including say making an order).
>
> This could be one or a series of Processes with different work inputs, and also of course Transfers/Exchanges, maybe first between the supplier and the coop, then between the coop and each orderer?
>
> A "work order" could be a set of processes that together create one or more things, like say an order. I think we will need something like work order, to group processes into a logical grouping with an output, which is what you are using the purchase group for. This might be like the little-p process.

re-reading your comments with fresh context @fosterlynn, i like your idea to approach with "work streams", interested in how to apply that as a data model. do you have data model examples of this in NRP or Value Flows?

**Comment by ahdinosaur** [comment]
found some relevant discussions in Value Flows issues:

- https://github.com/valueflows/valueflows/issues/174 
- https://github.com/valueflows/valueflows/issues/148
- https://github.com/valueflows/valueflows/issues/109
- https://github.com/valueflows/valueflows/issues/106

from what i understand, we want to model the entire order process as a series of steps that connect outputs from the previous steps to the inputs of the next step, with each step having input work actions by the agent acting as order facilitator using their hours as a resource.

so at a high level something like:

```yml
- supplier inventory entry process:
  - inputs:
    - facilitator work hours
  - outputs:
    - supplier resource types
    - supplier plans to sell resource types
- for each consumer, pre-buy intent process:
  - inputs:
    - supplier resource types
    - supplier plans to sell resource types
    - facilitator work hours
    - consumer work hours
  - outputs:
    - consumer pre-buy intent
- group buy tweaking process:
  - inputs:
    - consumer intents by each consumer
    - facilitator work hours
  - outputs:
    - group buy plan
- group order send:
  - inputs:
    - group buy plan
    - facilitator work hours
  - outputs:
    - group order
```

:heart_eyes_cat:

directly modelling these "work streams" could be how we handle both notifications and an audit log. the best part about this approach is that it matches perfectly with the next stage of the app workflow: receiving the order, delegating packing tasks, doing packing, hosting pick-up, doing pick-up, etc. should also work well with keeping track of any one-off tasks like sending emails or editing details or bringing containers. /cc @agentlewis
